import type { AdminAnalyticsScreen } from "@/components/admin/AdminAnalytics";

export const analyticsRanges = [
    "TODAY",
    "YESTERDAY",
    "LAST WEEK",
    "LAST MONTH",
    "LAST QUARTER",
    "LAST YEAR",
];

const reportOptions = [
    "Monthly Report",
    "3-Month Report",
    "6-Month Report",
    "Yearly Report",
];

const performanceLabels = [
    "26 Feb",
    "27 Feb",
    "28 Feb",
    "1 Mar",
    "2 Mar",
    "3 Mar",
    "4 Mar",
];

export const adminAnalyticsScreens = {
    products: {
        eyebrow: "ANALYTICS",
        title: "Products",
        subtitle: "Track sell-through, category mix, and the strongest performing SKUs.",
        activeRange: "TODAY",
        ranges: analyticsRanges,
        chartTitle: "PRODUCT PERFORMANCE",
        chartLabels: performanceLabels,
        tooltipLabel: "4 Mar 2026",
        series: [
            { label: "Items Sold", color: "#E6C979", active: true, values: [21, 23, 44, 27, 29, 24, 31], format: "number" },
            { label: "Net Sales", color: "#4A90C4", values: [18186, 20384, 38169, 23781, 26629, 23382, 28677], format: "currency" },
            { label: "Orders", color: "#C87A5A", values: [14, 16, 31, 19, 21, 18, 23], format: "number" },
        ],
        table: {
            title: "PRODUCTS",
            minWidthClassName: "min-w-[1220px]",
            searchPlaceholder: "Search product...",
            searchWidthClassName: "w-full sm:w-[280px]",
            columns: [
                { key: "productTitle", label: "PRODUCT TITLE", align: "left", font: "raleway", tone: "primary", weightClassName: "font-medium", className: "min-w-[220px]" },
                { key: "sku", label: "SKU", align: "center", font: "raleway", tone: "muted", className: "min-w-[110px]" },
                { key: "itemsSold", label: "ITEMS SOLD", align: "center", font: "cinzel", tone: "primary", className: "min-w-[110px]" },
                { key: "netSold", label: "NET SOLD", align: "center", font: "cinzel", tone: "primary", className: "min-w-[110px]" },
                { key: "netSales", label: "NET SALES", align: "center", font: "cinzel", tone: "primary", className: "min-w-[140px]" },
                { key: "orders", label: "ORDERS", align: "center", font: "cinzel", tone: "primary", className: "min-w-[110px]" },
                { key: "category", label: "CATEGORY", align: "center", font: "raleway", tone: "muted", className: "min-w-[110px]" },
                { key: "variations", label: "VARIATIONS", align: "center", font: "cinzel", tone: "primary", className: "min-w-[110px]" },
                { key: "price", label: "PRICE", align: "center", font: "cinzel", tone: "primary", className: "min-w-[110px]" },
            ],
            rows: [
                { id: "empire-oversized-tee", cells: { productTitle: "Empire Oversized Tee", sku: "ALB-EMT", itemsSold: "312", netSold: "312", netSales: "₹4,05,588", orders: "186", category: "T-Shirts", variations: "6", price: "₹1,299" } },
                { id: "pantheon-hoodie", cells: { productTitle: "Pantheon Hoodie", sku: "ALB-PHH", itemsSold: "248", netSold: "248", netSales: "₹5,45,352", orders: "162", category: "Hoodies", variations: "5", price: "₹2,199" } },
                { id: "medusa-crop-tee", cells: { productTitle: "Medusa Crop Tee", sku: "ALB-MCT", itemsSold: "186", netSold: "186", netSales: "₹2,23,014", orders: "126", category: "T-Shirts", variations: "4", price: "₹1,199" } },
                { id: "atlas-drop-shoulder", cells: { productTitle: "Atlas Drop Shoulder", sku: "ALB-ADS", itemsSold: "142", netSold: "142", netSales: "₹2,12,858", orders: "98", category: "T-Shirts", variations: "4", price: "₹1,499" } },
                { id: "olympus-oversized-hoodie", cells: { productTitle: "Olympus Oversized Hoodie", sku: "ALB-OOH", itemsSold: "108", netSold: "108", netSales: "₹2,69,892", orders: "74", category: "Hoodies", variations: "3", price: "₹2,499" } },
                { id: "cerberus-raglan", cells: { productTitle: "Cerberus Raglan", sku: "ALB-CRG", itemsSold: "92", netSold: "92", netSales: "₹1,28,708", orders: "58", category: "T-Shirts", variations: "3", price: "₹1,399" } },
                { id: "product-total", isTotal: true, cells: { productTitle: "TOTAL", sku: "", itemsSold: "2,108", netSold: "2,108", netSales: "₹18,42,300", orders: "1,284", category: "—", variations: "—", price: "—" } },
            ],
        },
    },
    revenue: {
        eyebrow: "ANALYTICS",
        title: "Revenue",
        subtitle: "Review gross sales, coupon impact, and net revenue movement over time.",
        activeRange: "TODAY",
        ranges: analyticsRanges,
        chartTitle: "REVENUE BREAKDOWN",
        chartLabels: ["25 Feb", "26 Feb", "27 Feb", "28 Feb", "1 Mar", "2 Mar", "3 Mar", "4 Mar"],
        tooltipLabel: "4 Mar 2026",
        series: [
            { label: "Gross Sales", color: "#E6C979", active: true, values: [14289, 18186, 20784, 40269, 24681, 27279, 23382, 29877], format: "currency" },
            { label: "Coupons", color: "#C86B6B", values: [300, 0, 400, 2100, 900, 650, 0, 1200], format: "currency" },
            { label: "Net Sales", color: "#4A90C4", active: true, values: [13989, 18186, 20384, 38169, 23781, 26629, 23382, 28677], format: "currency" },
            { label: "Total Sales", color: "#4CAF7D", values: [15240, 19450, 22460, 41860, 25740, 28490, 24620, 31720], format: "currency" },
        ],
        table: {
            title: "REVENUE",
            minWidthClassName: "min-w-[980px]",
            reportOptions,
            columns: [
                { key: "date", label: "DATE", align: "left", font: "raleway", tone: "primary", className: "min-w-[140px]" },
                { key: "orders", label: "ORDERS", align: "center", font: "cinzel", tone: "primary", className: "min-w-[90px]" },
                { key: "grossSales", label: "GROSS SALES", align: "center", font: "cinzel", tone: "primary", className: "min-w-[140px]" },
                { key: "coupons", label: "COUPONS", align: "center", font: "cinzel", tone: "primary", className: "min-w-[120px]" },
                { key: "netSales", label: "NET SALES", align: "center", font: "cinzel", tone: "primary", className: "min-w-[140px]" },
                { key: "totalSales", label: "TOTAL SALES", align: "center", font: "cinzel", tone: "primary", className: "min-w-[140px]" },
            ],
            rows: [
                { id: "rev-4-mar", cells: { date: "4 Mar 2026", orders: "23", grossSales: "₹29,877", coupons: "₹1,200", netSales: "₹28,677", totalSales: "₹28,677" } },
                { id: "rev-3-mar", cells: { date: "3 Mar 2026", orders: "18", grossSales: "₹23,382", coupons: "₹0", netSales: "₹23,382", totalSales: "₹23,382" } },
                { id: "rev-2-mar", cells: { date: "2 Mar 2026", orders: "21", grossSales: "₹27,279", coupons: "₹650", netSales: "₹26,629", totalSales: "₹26,629" } },
                { id: "rev-1-mar", cells: { date: "1 Mar 2026", orders: "19", grossSales: "₹24,681", coupons: "₹900", netSales: "₹23,781", totalSales: "₹23,781" } },
                { id: "rev-28-feb", cells: { date: "28 Feb 2026", orders: "31", grossSales: "₹40,269", coupons: "₹2,100", netSales: "₹38,169", totalSales: "₹38,169" } },
                { id: "rev-27-feb", cells: { date: "27 Feb 2026", orders: "16", grossSales: "₹20,784", coupons: "₹400", netSales: "₹20,384", totalSales: "₹20,384" } },
                { id: "rev-26-feb", cells: { date: "26 Feb 2026", orders: "14", grossSales: "₹18,186", coupons: "₹0", netSales: "₹18,186", totalSales: "₹18,186" } },
                { id: "rev-25-feb", cells: { date: "25 Feb 2026", orders: "11", grossSales: "₹14,289", coupons: "₹300", netSales: "₹13,989", totalSales: "₹13,989" } },
                { id: "rev-total", isTotal: true, cells: { date: "TOTAL", orders: "1,284", grossSales: "₹16,68,516", coupons: "₹47,480", netSales: "₹16,21,036", totalSales: "₹18,42,300" } },
            ],
        },
    },
    orders: {
        eyebrow: "ANALYTICS",
        title: "Order",
        subtitle: "Monitor daily order volume, customer throughput, and basket performance.",
        activeRange: "TODAY",
        ranges: analyticsRanges,
        chartTitle: "ORDER ANALYTICS",
        chartLabels: performanceLabels,
        tooltipLabel: "4 Mar 2026",
        series: [
            { label: "Orders", color: "#E6C979", active: true, values: [14, 16, 31, 19, 21, 18, 23], format: "number" },
            { label: "Net Sales", color: "#4A90C4", values: [18186, 20384, 38169, 23781, 26629, 23382, 28677], format: "currency" },
            { label: "Average Order Value", color: "#4CAF7D", values: [1299, 1274, 1231, 1252, 1268, 1299, 1247], format: "currency" },
            { label: "Average Items Per Order", color: "#C87A5A", values: [1.5, 1.4, 1.4, 1.4, 1.4, 1.3, 1.3], format: "decimal" },
        ],
        table: {
            title: "ORDERS",
            minWidthClassName: "min-w-[1120px]",
            reportOptions,
            columns: [
                { key: "date", label: "DATE", align: "left", font: "raleway", tone: "primary", className: "min-w-[140px]" },
                { key: "orders", label: "ORDERS", align: "center", font: "cinzel", tone: "primary", className: "min-w-[120px]" },
                { key: "customers", label: "CUSTOMERS", align: "center", font: "raleway", tone: "muted", className: "min-w-[130px]" },
                { key: "products", label: "PRODUCT(S)", align: "center", font: "raleway", tone: "muted", className: "min-w-[130px]" },
                { key: "itemsSold", label: "ITEMS SOLD", align: "center", font: "cinzel", tone: "primary", className: "min-w-[120px]" },
                { key: "coupons", label: "COUPON(S)", align: "center", font: "raleway", tone: "muted", className: "min-w-[120px]" },
                { key: "netSales", label: "NET SALES", align: "center", font: "cinzel", tone: "primary", className: "min-w-[140px]" },
            ],
            rows: [
                { id: "orders-4-mar", cells: { date: "4 Mar 2026", orders: "23", customers: "23 customers", products: "28 products", itemsSold: "31 items", coupons: "2 coupons", netSales: "₹28,677" } },
                { id: "orders-3-mar", cells: { date: "3 Mar 2026", orders: "18", customers: "18 customers", products: "22 products", itemsSold: "24 items", coupons: "0", netSales: "₹23,382" } },
                { id: "orders-2-mar", cells: { date: "2 Mar 2026", orders: "21", customers: "21 customers", products: "25 products", itemsSold: "29 items", coupons: "1 coupon", netSales: "₹26,629" } },
                { id: "orders-1-mar", cells: { date: "1 Mar 2026", orders: "19", customers: "19 customers", products: "24 products", itemsSold: "27 items", coupons: "2 coupons", netSales: "₹23,781" } },
                { id: "orders-28-feb", cells: { date: "28 Feb 2026", orders: "31", customers: "31 customers", products: "37 products", itemsSold: "44 items", coupons: "4 coupons", netSales: "₹38,169" } },
                { id: "orders-27-feb", cells: { date: "27 Feb 2026", orders: "16", customers: "16 customers", products: "20 products", itemsSold: "23 items", coupons: "1 coupon", netSales: "₹20,384" } },
                { id: "orders-26-feb", cells: { date: "26 Feb 2026", orders: "14", customers: "14 customers", products: "18 products", itemsSold: "21 items", coupons: "0", netSales: "₹18,186" } },
                { id: "orders-total", isTotal: true, cells: { date: "TOTAL", orders: "1,284 orders", customers: "—", products: "—", itemsSold: "2,108", coupons: "84 coupons", netSales: "₹16,21,036" } },
            ],
        },
    },
    categories: {
        eyebrow: "ANALYTICS",
        title: "Category",
        subtitle: "Compare category demand, sales contribution, and order concentration.",
        activeRange: "TODAY",
        ranges: analyticsRanges,
        chartTitle: "CATEGORY PERFORMANCE",
        chartLabels: performanceLabels,
        tooltipLabel: "4 Mar 2026",
        series: [
            { label: "Items Sold", color: "#E6C979", active: true, values: [21, 23, 44, 27, 29, 24, 31], format: "number" },
            { label: "Net Sales", color: "#4A90C4", values: [18186, 20384, 38169, 23781, 26629, 23382, 28677], format: "currency" },
            { label: "Orders", color: "#C87A5A", values: [14, 16, 31, 19, 21, 18, 23], format: "number" },
        ],
        table: {
            title: "CATEGORIES",
            minWidthClassName: "min-w-[760px]",
            searchPlaceholder: "Search category...",
            searchWidthClassName: "w-full sm:w-[240px]",
            reportOptions,
            columns: [
                { key: "category", label: "CATEGORY", align: "left", font: "raleway", tone: "primary", weightClassName: "font-medium", className: "min-w-[160px]" },
                { key: "itemsSold", label: "ITEMS SOLD", align: "center", font: "cinzel", tone: "primary", className: "min-w-[120px]" },
                { key: "netSales", label: "NET SALES", align: "center", font: "cinzel", tone: "primary", className: "min-w-[140px]" },
                { key: "products", label: "PRODUCTS", align: "center", font: "cinzel", tone: "primary", className: "min-w-[110px]" },
                { key: "orders", label: "ORDERS", align: "center", font: "cinzel", tone: "primary", className: "min-w-[110px]" },
            ],
            rows: [
                { id: "category-tshirts", cells: { category: "T-Shirts", itemsSold: "1,204", netSales: "₹15,64,796", products: "14", orders: "724" } },
                { id: "category-hoodies", cells: { category: "Hoodies", itemsSold: "904", netSales: "₹19,85,796", products: "10", orders: "560" } },
                { id: "category-empty", cells: { category: "—", itemsSold: "0", netSales: "₹0", products: "0", orders: "0" } },
                { id: "category-total", isTotal: true, cells: { category: "TOTAL", itemsSold: "2,108", netSales: "₹35,50,592", products: "24", orders: "1,284" } },
            ],
        },
    },
} satisfies Record<string, AdminAnalyticsScreen>;
